### ISSUE TITLE
支持composer集成

### ISSUE THREAD

**Issue by shikuntian** [Baidu-AIP/php-sdk#2]
小伙伴们可以集成下composer么

**Comment by iMuduo** [comment]
接下来会支持的

**Comment by qbhy** [comment]
https://github.com/qbhy/baidu-aip-sdk 百度AI开放平台php-sdk，支持composer，使用 foundation-sdk 3.0 开发。欢迎star。 @shikuntian @iMuduo 
> 而且支持 laravel/lumen 哦

**Comment by iMuduo** [comment]
官方已支持 composer require baidu/aip-sdk

**Comment by mengerzhuanyong** [comment]
composer 2.x 找不到包呀，只能在1.x里用吗
![image](https://user-images.githubusercontent.com/19523478/111129316-e81ec100-85b0-11eb-8101-f3ad6db2ee20.png)
@iMuduo
