### ISSUE TITLE
Please use namespace for PHP

### ISSUE THREAD

**Issue by whuhacker** [Baidu-AIP/php-sdk#5]
namespace is supported after PHP 5.3, and been widely used by PHP 7+.

Please namespace your SDK so that we can import it to our project via `use` instead of old style `require_once`

**Comment by YangYongAn** [comment]
没有命名空间真的很难受,百度大厂的东西怎么这么随意

**Comment by weishuiliang** [comment]
真是很醉，namespace都没有，活在过去年代（起码4年前）

**Comment by PeterPanZH** [comment]
抱歉Github上的开源代码实在是没有人力维护，如果需要最新版本的SDK请前往 https://ai.baidu.com/ 获取，感谢理解与支持。
